version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://mahir:mahir1453@cluster0.4sjt4.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=sizin_gizli_anahtariniz
      - PORT=5000
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server 