version: '3.8'

services:
  client:
    build: 
      context: ./client
      args:
        - REACT_APP_API_URL=https://chatapi.ipsstech.com.tr
    networks:
      - app-network

  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb+srv://mahir:mahir1453@cluster0.4sjt4.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=sizin_gizli_anahtariniz
      - PORT=5000
      - NODE_ENV=production
      - CLIENT_URL=https://chat.ipsstech.com.tr
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
    depends_on:
      - client
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 